name: Build rootfs

on:
  push:
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build rootfs
        run: |
          git clone https://github.com/aarchd/arch-bootstrap --depth 1
          sudo ./arch-bootstrap/arch-bootstrap.sh -a "aarch64" -r "http://hu.mirror.archlinuxarm.org" rootfs

      - name: Set up aarchd repo and autologin
        run: |
          git clone https://github.com/aarchd/arch-install-scripts --depth 1
          sudo make -j4 -C arch-install-scripts install
          sudo mount --bind "$PWD" rootfs/mnt
          sudo arch-chroot rootfs /bin/bash -c "\
              /mnt/setup-aarchd-repo.sh && \
              /mnt/setup-autologin.sh"
          sudo umount rootfs/mnt

      - name: Pack rootfs
        run: sudo tar czf rootfs.tar.gz -C rootfs .

      - name: Delete previous release and tag (if exists)
        run: |
          gh release delete latest -y || true
          git push --delete origin refs/tags/latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Release"
          tag_name: "latest"
          files: rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


