name: Build rootfs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-publish:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build rootfs
        run: |
          git clone https://github.com/aarchd/arch-bootstrap --depth 1
          sudo ./arch-bootstrap/arch-bootstrap.sh -a "aarch64" -r "http://hu.mirror.archlinuxarm.org" rootfs

      - name: Set up aarchd repo and autologin
        run: |
          git clone https://github.com/aarchd/arch-install-scripts --depth 1
          sudo make -j4 -C arch-install-scripts install
          sudo mount --bind "$PWD" rootfs/mnt
          sudo arch-chroot rootfs /bin/bash -c "\
              /mnt/setup-aarchd-repo.sh && \
              /mnt/setup-autologin.sh"
          sudo umount rootfs/mnt

      - name: Log in to GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker
        run: |
          sudo docker build -t ghcr.io/${{ github.repository_owner }}/aarchd:latest .
          docker push ghcr.io/${{ github.repository_owner }}/aarchd:latest

      - name: Pack rootfs
        run: sudo tar -cf rootfs.tar.zst -C rootfs . --use-compress-program="zstd -19 -T0"

      - name: Delete previous release and tag (if exists)
        run: |
          gh release delete latest -y || true
          git push --delete origin refs/tags/latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Release"
          tag_name: "latest"
          files: rootfs.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


